### ISSUE TITLE
In header, the count text is coming of same colour as of wishlist.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Yakir-Internal-Speed-Theme-17-June-2022#3]
**Actual result:**
In header, the count text is coming of same colour as of wishlist.
![image](https://user-images.githubusercontent.com/102131636/174028368-df06f7b4-0a2b-4a6e-b782-c3086d626f05.png)

**Expected result:**
The count have to be visible properly in the wishlist count.
![image](https://user-images.githubusercontent.com/102131636/174028536-4c597a5f-5f34-4b74-b1a9-8ec8aa07b612.png)

**Comment by devRitikTamrakar** [comment]
will be resolved once we will publish the theme

**Comment by sudhanshu0603** [comment]
ok,

**Comment by sudhanshu0603** [comment]
ok, resolved
